name: SeniorTransfer
main: pers.tany.seniortransfer.Main
version: 1.0.3
author: tany
depend: [ YukiNoaAPI ]
description: GTA5版接管式传送
commands:
  SeniorTransfer:
    usage: /SeniorTransfer
    aliases: [ st ]